# Generated by Django 5.2.3 on 2025-07-01 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NUPO Consult Ltd', max_length=100)),
                ('tagline', models.CharField(default="Rwanda's Engineering Partner", max_length=200)),
                ('description', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='info@nupoconsult.com', max_length=254)),
                ('address', models.TextField(default='')),
                ('working_hours', models.CharField(default='Mon - Fri: 8:00 AM - 6:00 PM', max_length=100)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.CreateModel(
            name='CompanyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.IntegerField(default=10)),
                ('projects_completed', models.IntegerField(default=150)),
                ('happy_clients', models.IntegerField(default=50)),
                ('support_hours', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Statistics',
                'verbose_name_plural': 'Company Statistics',
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('quote', 'Request Quote'), ('consultation', 'Consultation Request'), ('partnership', 'Partnership Inquiry'), ('career', 'Career Inquiry'), ('complaint', 'Complaint')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='')),
                ('project_budget', models.CharField(blank=True, default='', max_length=100)),
                ('project_timeline', models.CharField(blank=True, default='', max_length=100)),
                ('is_responded', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='News Article', max_length=200)),
                ('slug', models.SlugField(default='news-article', unique=True)),
                ('article_type', models.CharField(choices=[('news', 'Company News'), ('award', 'Awards & Recognition'), ('project', 'Project Updates'), ('industry', 'Industry Insights'), ('sustainability', 'Sustainability'), ('training', 'Training & Education')], default='news', max_length=20)),
                ('excerpt', models.TextField(default='', max_length=300)),
                ('content', models.TextField(default='')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('icon_class', models.CharField(default='fas fa-newspaper', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta_title', models.CharField(blank=True, default='', max_length=200)),
                ('meta_description', models.CharField(blank=True, default='', max_length=300)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Project Name', max_length=200)),
                ('slug', models.SlugField(default='project-slug', unique=True)),
                ('client', models.CharField(default='Client Name', max_length=100)),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('infrastructure', 'Infrastructure'), ('institutional', 'Institutional')], default='commercial', max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('design', 'Design Phase'), ('construction', 'Under Construction'), ('completed', 'Completed'), ('maintenance', 'Maintenance Phase')], default='planning', max_length=20)),
                ('description', models.TextField(default='')),
                ('location', models.CharField(default='', max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='home', max_length=50, unique=True)),
                ('meta_title', models.CharField(default='', max_length=200)),
                ('meta_description', models.CharField(default='', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=500)),
                ('og_title', models.CharField(blank=True, default='', max_length=200)),
                ('og_description', models.CharField(blank=True, default='', max_length=300)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('canonical_url', models.URLField(blank=True, default='')),
                ('robots_meta', models.CharField(default='index, follow', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General Services', max_length=100)),
                ('slug', models.SlugField(default='general-services', unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_class', models.CharField(default='fas fa-cog', help_text="FontAwesome icon class (e.g., 'fas fa-search')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=100)),
                ('client_company', models.CharField(blank=True, default='', max_length=100)),
                ('client_position', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField(default='')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-subscribed_date'], 'verbose_name': 'Newsletter Subscription', 'verbose_name_plural': 'Newsletter Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='subscribed_at',
            new_name='subscribed_date',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.AlterUniqueTogether(
            name='newsletter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='partner',
            name='website',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='title',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='unsubscribed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('government', 'Government Agency'), ('private', 'Private Sector'), ('ngo', 'NGO/Non-Profit'), ('academic', 'Academic Institution'), ('international', 'International Organization'), ('supplier', 'Supplier/Vendor')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='partnership_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.SlugField(default='partner-slug', unique=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of service features'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='fas fa-cog', help_text='FontAwesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='price_range',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='service-slug', unique=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.CharField(default='Team Member', max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_type',
            field=models.CharField(choices=[('ceo', 'Chief Executive Officer'), ('director', 'Director'), ('manager', 'Manager'), ('engineer', 'Engineer'), ('consultant', 'Consultant'), ('supervisor', 'Supervisor'), ('specialist', 'Specialist')], default='engineer', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='qualifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teammember',
            name='short_bio',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(default='team-member', unique=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(default='Partner Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='Service Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='Team Member', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='services_interested',
            field=models.ManyToManyField(blank=True, to='main.service'),
        ),
        migrations.AddField(
            model_name='project',
            name='services_provided',
            field=models.ManyToManyField(blank=True, to='main.service'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, to='main.teammember'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.servicecategory'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service'),
        ),
    ]
